import pandas as pd
import ast
import re
import os
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report
# EVALUATE PERFORMANCES BY READING THE CSV OF PREDICTIONS GENERATED BY THE PIPELINE AND CALCULATING METRICS

def clean_eval_string(text):
    """Cleans the medical text by removing punctuation and extra spaces."""
    if not isinstance(text, str):
        return ""
    text = text.lower().strip()
    text = re.sub(r'\s*([-,.\/])\s*', r'\1', text)
    text = re.sub(r'[^\w\s]', '', text)
    return " ".join(text.split())

def extract_valid_options(raw_truth):

    """
    Cuts and extracts all valid text strings from the ground truth, 
    regardless of the level of bracket nesting. 
    """
    text_raw = str(raw_truth).strip()
    if text_raw == "N/A" or not text_raw:
        return []
        
    options = re.findall(r"['\"]([^'\"]+)['\"]", text_raw)
    
    if not options:
        cleaned = text_raw.replace('[', '').replace(']', '').strip()
        if cleaned:
            options = [cleaned]
            
    return [clean_eval_string(opt) for opt in options if opt]

def calculate_performances_pipeline(csv_filepath, output_csv="./results/multitask_metrics_summary.csv"):
    if not os.path.exists(csv_filepath):
        print(f"Error : File of prediction {csv_filepath} does not exist.")
        return

    df = pd.read_csv(csv_filepath)
    
    # Eliminate fallback or error lines
    df = df[~df["Pipeline Predicted Answer"].str.contains("fallback|Skipped|Error", na=False, case=False)]
    
    print(f"Evaluation on {len(df)} valid questions (Yes/No, Factoid, List)...")
    
    metrics_data = {"Metric Name": [], "Question Type": [], "Value": []}
    
    # ==========================================
    # EVALUATION YES/NO
    # ==========================================
    df_yn = df[df["Question Type"] == "yesno"]

    if not df_yn.empty:
        y_true = (
            df_yn["Ground Truth Answer"]
            .apply(lambda x: str(x).lower().strip("[]'\" "))
        )

        y_pred = (
            df_yn["Pipeline Predicted Answer"]
            .astype(str)
            .str.lower()
            .str.strip()
        )

        accuracy_yn = (y_true == y_pred).mean()

        macro_f1 = f1_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        )

        precision_macro = precision_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        )

        recall_macro = recall_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        )

        print(f"\n--- PERFORMANCE YES/NO (Total: {len(df_yn)}) ---")
        print(f"Accuracy      : {accuracy_yn * 100:.2f}%")
        print(f"Macro Precision : {precision_macro * 100:.2f}%")
        print(f"Macro Recall    : {recall_macro * 100:.2f}%")
        print(f"Macro F1        : {macro_f1 * 100:.2f}%")

        print("\nClassification Report")
        print(
            classification_report(
                y_true,
                y_pred,
                zero_division=0
            )
        )

        metrics_data["Metric Name"].extend([
            "Accuracy",
            "Macro Precision",
            "Macro Recall",
            "Macro F1"
        ])

        metrics_data["Question Type"].extend([
            "yesno",
            "yesno",
            "yesno",
            "yesno"
        ])

        metrics_data["Value"].extend([
            accuracy_yn,
            precision_macro,
            recall_macro,
            macro_f1
        ])
        
        # ==========================================
        # EVALUATION FACTOID
        # ==========================================
        df_fact = df[df["Question Type"] == "factoid"]
        if not df_fact.empty:
            exact_matches = 0
            for _, row in df_fact.iterrows():
                pred = clean_eval_string(row["Pipeline Predicted Answer"])
                if pred == "no extraction found" or not pred:
                    continue
                    
                truths = extract_valid_options(row["Ground Truth Answer"])
                
                if any(pred in t or t in pred for t in truths if t):
                    exact_matches += 1
                    
            strict_accuracy = exact_matches / len(df_fact)
            print(f"\n--- PERFORMANCE FACTOID (Total: {len(df_fact)}) ---")
            print(f"Strict Accuracy (Flexible Match) : {strict_accuracy * 100:.2f}%")
            metrics_data["Metric Name"].append("Strict Accuracy (EM)")
            metrics_data["Question Type"].append("factoid")
            metrics_data["Value"].append(strict_accuracy)

    # ==========================================
    # EVALUATION LIST 
    # ==========================================
    df_list = df[df["Question Type"] == "list"]
    if not df_list.empty:
        total_precision = 0
        total_recall = 0
        
        for _, row in df_list.iterrows():
            raw_pred = row["Pipeline Predicted Answer"]
            
            if not isinstance(raw_pred, str) or not raw_pred.strip():
                preds_raw_list = []
            elif " | " in raw_pred:
                # Split the predictions based on the " | " separator
                preds_raw_list = raw_pred.split(" | ")
            elif raw_pred.startswith("[") and raw_pred.endswith("]"):
                try:
                    preds_raw_list = ast.literal_eval(raw_pred)
                except Exception:
                    preds_raw_list = re.findall(r"['\"]([^'\"]+)['\"]", raw_pred)
            else:
                preds_raw_list = [raw_pred]

            # Clean each prediction in the list and filter out empty residues
            preds_list = [clean_eval_string(p) for p in preds_raw_list if p]
            preds_list = [p for p in preds_list if p != "no extraction found" and p != ""]
            
            truths = extract_valid_options(row["Ground Truth Answer"])
            
            if not preds_list:
                total_precision += 0
                total_recall += 0
                continue

            # Calculate True Positives (TP)
            true_positives = 0
            matched_truths = set()
            
            for p in preds_list:
                for idx, t in enumerate(truths):
                    if idx not in matched_truths:
                        if p in t or t in p:
                            true_positives += 1
                            matched_truths.add(idx)
                            break 
            
            # Calculate precision and recall for this question
            precision = true_positives / len(preds_list) if len(preds_list) > 0 else 0
            recall = true_positives / len(truths) if len(truths) > 0 else 0
            
            total_precision += precision
            total_recall += recall
            
        mean_precision = total_precision / len(df_list)
        mean_recall = total_recall / len(df_list)
        f1_list = (2 * mean_precision * mean_recall) / (mean_precision + mean_recall) if (mean_precision + mean_recall) > 0 else 0
        
        print(f"\n--- PERFORMANCE LIST (Total: {len(df_list)}) ---")
        print(f"Precision moyenne : {mean_precision * 100:.2f}%")
        print(f"Recall moyen      : {mean_recall * 100:.2f}%")
        print(f"F1-Score moyen    : {f1_list * 100:.2f}%")
        
        metrics_data["Metric Name"].extend(["Precision", "Recall", "F1-Score"])
        metrics_data["Question Type"].extend(["list", "list", "list"])
        metrics_data["Value"].extend([mean_precision, mean_recall, f1_list])

    # ==========================================
    # SAVE
    # ==========================================
    if metrics_data["Metric Name"]:
        os.makedirs(os.path.dirname(output_csv), exist_ok=True)
        df_metrics = pd.DataFrame(metrics_data)
        df_metrics["Value (%)"] = df_metrics["Value"] * 100
        df_metrics = df_metrics.drop(columns=["Value"])
        df_metrics.to_csv(output_csv, index=False)
        print(f"\n[INFO] Rapport des métriques sauvegardé sous : {output_csv}")


if __name__ == "__main__":
    print("=== PERFORMANCE OF MULTITASK MODEL ===")
    calculate_performances_pipeline(
        csv_filepath="./results/multitask_pipeline_predictions_combined.csv",
        output_csv="./results/multitask_metrics_summary.csv"
    )
